GET http://localhost:5000/products

###
GET http://localhost:5000/products/1

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "namaProduct": "Kipas Angin",
    "deskripsiProduct": "Baru",
   "hargaProduct": "120000",
    "persediaan": "20"
}

###
PATCH http://localhost:5000/products/1
Content-Type: application/json

{
     "namaProduct": "Meja",
    "deskripsiProduct": "Baru",
   "hargaProduct": "120000",
    "persediaan": "20"
}

###
DELETE http://localhost:5000/products/4